#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
#

Name:       weston

# >> macros
# << macros

Summary:    weston compositor
Version:    1.8.0
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://wayland.freedesktop.org/
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(wayland-server) >= 1.8.0
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(libhardware)
BuildRequires:  pkgconfig(wayland-egl)
BuildRequires:  pkgconfig(hybris-egl-platform)
BuildRequires:  pkgconfig(android-headers)
BuildRequires:  libjpeg-turbo-devel
BuildRequires:  pam-devel

%description
weston compositor

%build
# >> build pre
# << build pre

%reconfigure --disable-static \
    --disable-documentation --disable-xwayland --disable-x11-compositor \
    --disable-drm-compositor --disable-rpi-compositor --disable-fbdev-compositor \
    --enable-hwcomposer-compositor

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post

# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%{_bindir}/*
%{_libdir}/weston/*
%{_libdir}/pkgconfig/*
%{_libexecdir}/*
%{_datadir}/weston/*
%{_datadir}/man/*
%{_datadir}/wayland-sessions/weston.desktop
%{_includedir}/weston/*
# << files

